In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sc
import math

**Clearing data, removing duplicates and handling missing data.**

In [6]:
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)

#Load data
df = pd.read_csv('/content/drive/Othercomputers/ה-מחשב נייד שלי/Desktop/Python Project/old_data/high_tech_data.csv', index_col=0)

#Convert '-' to Nan
df = df.replace('-',np.NaN)

#Remove commas from salary column
df['Salary'] = df['Salary'].replace(',','', regex=True)

#Convert salary column from string to float 
df.Salary = pd.to_numeric(df['Salary'], errors='coerce')

#Convert experience column from string to float
df.Seniority = pd.to_numeric(df['Seniority'], errors='coerce')

#Fill NaN values as mean of seniority column and convert from float to integer
df.Seniority = df['Seniority'].fillna(math.ceil(df['Seniority'].mean())).astype(np.int64)

#Sort dataframe by date
df['Date'] = pd.to_datetime(df.Date)
df = df.sort_values('Date', ascending=False, ignore_index=True)

#Drop duplicated rows
df = df.drop_duplicates()

In [7]:
#List of the numeric columns
col_numeric = ['Experience', 'Salary']
  
#Find outliers at 4 std
outliers = df[df['Salary'] > df['Salary'].mean() + 4 * df['Salary'].std()]

#Get outliers that not make sense
seniority_outliers = outliers[df['Seniority'] < 7]
salary_outliers = outliers[df['Salary'] > 100000]

#Remove outliers that not make sense
df = df.drop(salary_outliers.index | seniority_outliers.index)

#Reset index
df = df.reset_index(drop=True)

#Export data
df.to_csv('high_tech_data1.csv', encoding='utf-8-sig')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  if __name__ == '__main__':

In [8]:
df

Output hidden; open in https://colab.research.google.com to view.